version: '3.8'

services:
  app:
    build: .
    container_name: vendure_db
    restart: always
    env_file:
      - .env.docker
    depends_on:
      - db
    ports:
      - "1311:1211"

  db:
    image: postgres:15
    container_name: vendure_app
    environment:
      POSTGRES_USER: eazylab
      POSTGRES_PASSWORD: Eazylab123
      POSTGRES_DB: vendure
    ports:
      - "5432:5432"
